/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class se_vbgt_jni_NativeRangeLib */

#ifndef _Included_se_vbgt_jni_NativeRangeLib
#define _Included_se_vbgt_jni_NativeRangeLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     se_vbgt_jni_NativeRangeLib
 * Method:    lowerHalf
 * Signature: ([I)[I
 */
JNIEXPORT jintArray JNICALL Java_se_vbgt_jni_NativeRangeLib_lowerHalf
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     se_vbgt_jni_NativeRangeLib
 * Method:    upperHalf
 * Signature: ([I)[I
 */
JNIEXPORT jintArray JNICALL Java_se_vbgt_jni_NativeRangeLib_upperHalf
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
